.TH iofs 2 "February 2019" YAX "KERNEL INTERFACES"
.SH NAME
iofs \- expose x86 interrupts to userspace
.SH SYNOPSYS
.BR 0 \- f
.SH DESCRIPTION
The root directory of this filesystem contains 16 pseudo\-files, one for each
hardware interrupt, named in lowercase hexadecimal. When open, they may be read,
one machine integer at a time, to return the number of interrupts of that kind
since the last read. When the read would return 0, instead it blocks until at
least one interrupt was triggered.
.PP
It is mounted by the kernel at
.B /
on startup. This location may be bound elsewhere afterwards.
.SH NOTE
Two processes should not open the same port or interrupt file at once. This may
result into serious race conditions and is likely undesired anyway.
.SH SEE ALSO
.BR intro (2),
.BR func (2)
.SH BUGS
The default mounting location is dumb.

