.TH noted 2 "December 2018" YAX "KERNEL INTERFACES"
.SH NAME
noted \- return from a note handler
.SH SYNOPSYS
.B #include <yax/nflags.h>
.PP
.BI "void noted(enum nflags " f ");"
.SH DESCRIPTION
Return to the kernel from a note handler.
.SH SEE ALSO
.BR intro (2),
.BR notify (2)
.SH BUGS
.I f
is ignored, and only
.B NCONT
behaviour is possible.

