#ifndef _YAX_FN_H
#define _YAX_FN_H

enum {
	MWANTSPTR = 1 << 16,
	MWANTSOFF = 2 << 16,
	MWANTSWR = 4 << 16
};
enum {
	MDEL = 0,
	MDUP = 1,
	MWALK = 2 | MWANTSPTR,
	MOPEN = 3,
	MSREAD = 4 | MWANTSPTR | MWANTSWR,
	MSWRITE = 5 | MWANTSPTR,
	MSEEK = 6,
	MPREAD = 7 | MWANTSPTR | MWANTSWR | MWANTSOFF,
	MPWRITE = 8 | MWANTSPTR | MWANTSOFF,
	MSTAT = 9 | MWANTSPTR | MWANTSWR,
	MWSTAT = 10 | MWANTSPTR,
	MIOCTL = 11
};

#endif /* _YAX_FN_H */

